// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw94QnFS7HSjfII1eLEyRzSHjlfiXYW5Q',
    appId: '1:727535963992:web:e9e29831a5fe07eb229f2d',
    messagingSenderId: '727535963992',
    projectId: 'flutterbullan',
    authDomain: 'flutterbullan.firebaseapp.com',
    storageBucket: 'flutterbullan.firebasestorage.app',
    measurementId: 'G-ZECGFBQJJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArWsk9jrL9_Uj1kmRgHwyP9_tFTQkDlGQ',
    appId: '1:727535963992:android:7d0b3b2b6be8726e229f2d',
    messagingSenderId: '727535963992',
    projectId: 'flutterbullan',
    storageBucket: 'flutterbullan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjh7cI0DEV2i2AYqP-vg-XWd0uWa4aVKM',
    appId: '1:727535963992:ios:3761aacb29891fb0229f2d',
    messagingSenderId: '727535963992',
    projectId: 'flutterbullan',
    storageBucket: 'flutterbullan.firebasestorage.app',
    iosBundleId: 'com.example.bullan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjh7cI0DEV2i2AYqP-vg-XWd0uWa4aVKM',
    appId: '1:727535963992:ios:3761aacb29891fb0229f2d',
    messagingSenderId: '727535963992',
    projectId: 'flutterbullan',
    storageBucket: 'flutterbullan.firebasestorage.app',
    iosBundleId: 'com.example.bullan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw94QnFS7HSjfII1eLEyRzSHjlfiXYW5Q',
    appId: '1:727535963992:web:45daa970fe867de5229f2d',
    messagingSenderId: '727535963992',
    projectId: 'flutterbullan',
    authDomain: 'flutterbullan.firebaseapp.com',
    storageBucket: 'flutterbullan.firebasestorage.app',
    measurementId: 'G-Z2R4MM3S8V',
  );

}